"""Murged availability table with artist table for easier maintainability

Revision ID: 3343aeed5b8b
Revises: 3addda2a56e5
Create Date: 2020-05-12 18:09:40.768217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3343aeed5b8b'
down_revision = '3addda2a56e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_availability')
    op.add_column('artists', sa.Column('monday', sa.Boolean(),
                                       server_default='true', nullable=False))
    op.add_column('artists', sa.Column('tuesday', sa.Boolean(),
                                       server_default='true', nullable=False))
    op.add_column('artists', sa.Column('wednesday', sa.Boolean(),
                                       server_default='true', nullable=False))
    op.add_column('artists', sa.Column('thursday', sa.Boolean(),
                                       server_default='true', nullable=False))
    op.add_column('artists', sa.Column('friday', sa.Boolean(),
                                       server_default='true', nullable=False))
    op.add_column('artists', sa.Column('saturday', sa.Boolean(),
                                       server_default='true', nullable=False))
    op.add_column('artists', sa.Column('sunday', sa.Boolean(),
                                       server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'monday')
    op.drop_column('artists', 'tuesday')
    op.drop_column('artists', 'wednesday')
    op.drop_column('artists', 'thursday')
    op.drop_column('artists', 'friday')
    op.drop_column('artists', 'saturday')
    op.drop_column('artists', 'sunday')
    op.create_table('artist_availability',
                    sa.Column('artist_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('monday', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.Column('tuesday', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.Column('wednesday', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.Column('thursday', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.Column('friday', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.Column('saturday', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.Column('sunday', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['artist_id'], [
                        'artists.id'], name='artist_availability_artist_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'artist_id', name='artist_availability_pkey')
                    )
    # ### end Alembic commands ###
