"""Altered genres to be not null

Revision ID: 3addda2a56e5
Revises: 81a055d158fc
Create Date: 2020-05-11 00:53:29.699306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3addda2a56e5'
down_revision = '81a055d158fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'genres',
                    existing_type=sa.VARCHAR(length=150),
                    nullable=False)
    op.alter_column('venues', 'genres',
                    existing_type=sa.VARCHAR(length=150),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
                    existing_type=sa.VARCHAR(length=150),
                    nullable=True)
    op.alter_column('artists', 'genres',
                    existing_type=sa.VARCHAR(length=150),
                    nullable=True)
    # ### end Alembic commands ###
